#language versions used to test src
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
services:
  - mysql

env:
  - MYSQL_DATABASE=travis_db MYSQL_USER=root MYSQL_PORT=3306 MYSQL_HOST=127.0.0.1 DATABASE_URL=mysql://$MYSQL_USER:@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE

#src dependencies installation
install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install mysqlclient

#running unit tests
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_db;'
  - gunicorn -w 4 wsgi:app -b 127.0.0.1:5000 -D
  - ps ax|grep gunicorn

# command to run tests
script:
  - pylint src/
  - flask --app=src/ db upgrade --directory src/migrations/
  - coverage run -m pytest && coverage report

after_script:
  - pkill gunicorn
  - ps ax|grep gunicorn