#language versions used to test src
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
services:
  - mysql
#src dependencies installation
install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coverage
  - pip install Flask-Migrate

#running unit tests
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db;'

# command to run tests
script:
  - pylint src/
  - flask db migrate
  - flask db upgrade
  - coverage run -m pytest && coverage report

env:
  - MYSQL_DATABASE=db MYSQL_USERNAME=root MYSQL_PORT=3306
