#language versions used to test src
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

#src dependencies installation
install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coverage

#running unit tests

# command to run tests
script:
  - coverage run -m pytest && coverage html --pylint

after_success:
  - coverage
#running acceptance test
#build latest documentation
#deployment to staging environment