#language versions used to test src
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

#src dependencies installation
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db;'

install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coverage
  
development:
  database: db
  username: travis
  password: 1111

test:
  adapter: mysql12
  database: db
  username: travis
  password: 1111
  encoding: utf8
#running unit tests

# command to run tests
script:
  - pylint src/
  - coverage run -m pytest && coverage report

env:
  - MYSQL_DATABASE=db MYSQL_PASSWORD=1111 MYSQL_USERNAME=travis MYSQL_PORT=3306
#  - coverage run -m pytest && coverage html --pylint
#after_success:
#running acceptance test
#build latest documentation
#deployment to staging environment