#language versions used to test src
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
services:
  - mysql
#src dependencies installation
install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coverage
  - pip install Flask-Migrate
  - pip install mysqlclient

#running unit tests
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis_db;'

# command to run tests
script:
  - pylint src/
  - flask --app=src/ db init
  - flask --app=src/ db migrate
  - flask --app=src/ db upgrade
  - coverage run -m pytest && coverage report

env:
  - MYSQL_DATABASE=travis_db MYSQL_USER=my MYSQL_PORT=3306 MYSQL_HOST=127.0.0.1 MYSQL_PASSWORD=1111 DATABASE_URL=mysql://$MYSQL_USER:$MYSQL_PASSWORD@$MYSQL_HOST:$MYSQL_PORT/$MYSQL_DATABASE
