#language versions used to test src
language: python
python:
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

#src dependencies installation
install: # command to install dependencies
  - pip install -r requirements.txt
  - pip install pylint
  - pip install coverage

#running unit tests

# command to run tests
script:
  - pylint src/
  - coverage run -m pytest && coverage report

env:
  - MYSQL_DATABASE=db MYSQL_PASSWORD=2332 MYSQL_USERNAME=den MYSQL_PORT=3306
#  - coverage run -m pytest && coverage html --pylint
#after_success:
#running acceptance test
#build latest documentation
#deployment to staging environment