"""empty message

Revision ID: 67b2ea5ac58b
Revises: 
Create Date: 2023-02-21 20:05:11.117043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b2ea5ac58b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Doctors',
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.Enum('THERAPIST', 'ORTHOPEDIST', 'SURGEON', 'RADIOLOGIST', name='specialty'), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('doctor_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('Patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('year_of_birth', sa.Integer(), nullable=True),
    sa.Column('kind_of_ache', sa.Enum('NONE', 'MILD', 'MIDDLE', 'STRONG', name='kindofache'), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['Doctors.doctor_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Patients')
    op.drop_table('Doctors')
    # ### end Alembic commands ###
