"""empty message

Revision ID: e5b22d6fa10b
Revises: 03e9fc893def
Create Date: 2023-03-03 09:01:05.818988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b22d6fa10b'
down_revision = '03e9fc893def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.drop_constraint('Patients_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Doctors', ['doctor_id'], ['doctor_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Patients_ibfk_1', 'Doctors', ['doctor_id'], ['doctor_id'])

    # ### end Alembic commands ###
